- src/Server/API/Startup.cs
- src/Server/API/appsettings.json
- src/Server/Modules/Catalog/Modules.Catalog.Infrastructure/Persistence/CatalogDbContext.cs
- src/Server/Modules/Catalog/Modules.Catalog.Infrastructure/Persistence/ModelBuilderExtensions.cs
- src/Server/Modules/Identity/Modules.Identity.Infrastructure/Extensions/ModelBuilderExtensions.cs
- src/Server/Modules/Identity/Modules.Identity.Infrastructure/Persistence/IdentityDbContext.cs
- src/Server/Shared/Shared.Infrastructure/Extensions/ModelBuilderExtensions.cs
- src/Server/Shared/Shared.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/Server/Shared/Shared.Infrastructure/Persistence/ApplicationDbContext.cs
- src/Server/Shared/Shared.Infrastructure/Persistence/ModuleDbContext.cs
- src/Server/Shared/Shared.Infrastructure/Persistence/PersistenceSettings.cs
- src/Server/Shared/Shared.Infrastructure/Persistence/ServiceCollectionExtensions.cs
Adds the ability to choose between MSSQL and Postgresql databases.
> Add PersistenceSettings for database selection (MSSQL or PostgreSQL)

- .gitignore
- src/Server/Modules/Accounting/Modules.Accounting.Core/Modules.Accounting.Core.csproj
- src/Server/Modules/Accounting/Modules.Accounting.Infrastructure/Modules.Accounting.Infrastructure.csproj
- src/Server/Modules/Accounting/Modules.Accounting/Modules.Accounting.csproj
- src/Server/Modules/Catalog/Modules.Catalog.Controllers/Modules.Catalog.csproj
- src/Server/Modules/Catalog/Modules.Catalog.Core/Modules.Catalog.Core.csproj
- src/Server/Modules/Catalog/Modules.Catalog.Infrastructure/Modules.Catalog.Infrastructure.csproj
- src/Server/Modules/Identity/Modules.Identity.Core/Modules.Identity.Core.csproj
- src/Server/Modules/Identity/Modules.Identity.Infrastructure/Modules.Identity.Infrastructure.csproj
- src/Server/Modules/Identity/Modules.Identity/Modules.Identity.csproj
- src/Server/Modules/Inventory/Modules.Inventory.Core/Modules.Inventory.Core.csproj
- src/Server/Modules/Inventory/Modules.Inventory.Infrastructure/Modules.Inventory.Infrastructure.csproj
- src/Server/Modules/Inventory/Modules.Inventory/Modules.Inventory.csproj
- src/Server/Modules/People/Modules.People.Core/Modules.People.Core.csproj
- src/Server/Modules/People/Modules.People.Infrastructure/Modules.People.Infrastructure.csproj
- src/Server/Modules/People/Modules.People/Modules.People.csproj
- src/Server/Modules/Sales/Modules.Sales.Core/Modules.Sales.Core.csproj
- src/Server/Modules/Sales/Modules.Sales.Infrastructure/Modules.Sales.Infrastructure.csproj
- src/Server/Modules/Sales/Modules.Sales/Modules.Sales.csproj
- src/Server/Shared/Shared.Application/Shared.Application.csproj
- src/Server/Shared/Shared.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/Server/Shared/Shared.Infrastructure/Shared.Infrastructure.csproj
> Revert "Fix: Include all project's xml comments for swagger"

- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/BrandsController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/CategoriesController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/ProductsController.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Commands/RemoveBrandCommand.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Commands/Validators/RegisterBrandCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Commands/Validators/RemoveBrandCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Commands/Validators/UpdateBrandCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Events/BrandEventHandler.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Events/BrandRegisteredEvent.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Events/BrandRemovedEvent.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Events/BrandUpdatedEvent.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Queries/GetAllPagedBrandsQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Queries/GetBrandByIdQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Queries/GetBrandImageQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Commands/RemoveCategoryCommand.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Commands/Validators/RegisterCategoryCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Commands/Validators/RemoveCategoryCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Commands/Validators/UpdateCategoryCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Queries/GetAllPagedCategoriesQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Queries/GetCategoryByIdQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Queries/GetCategoryImageQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Commands/RemoveProductCommand.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Commands/Validators/RegisterProductCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Commands/Validators/RemoveProductCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Commands/Validators/UpdateProductCommandValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/GetAllPagedProductsQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/GetProductByIdQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/GetProductImageQuery.cs
Also add `IStringLocalizer` to validators and `BrandEventHandler`.
> Fix: Fix setting query/command properties

- src/server/Modules/Identity/Modules.Identity/Controllers/RolesController.cs
> Update: Add GetClaimByIdAsync and GetAllClaimsAsync

- src/server/API/Startup.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Extensions/ModuleExtensions.cs
- src/server/Modules/Identity/Modules.Identity.Core/Helpers/ClaimExtensions.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Permissions/PermissionAuthorizationHandler.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Permissions/PermissionPolicyProvider.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Permissions/PermissionRequirement.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Persistence/IdentityDbSeeder.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Services/RoleService.cs
- src/server/Shared/Shared.Core/Constants/ApplicationClaimType.cs
Just updated some of the class namespaces to match the correct path.
> Namespace Refactoring

- src/client/src/app/modules/admin/admin-routing.module.ts
- src/client/src/app/modules/admin/catalog/api/brand-api.service.ts
- src/client/src/app/modules/admin/catalog/api/category-api.service.ts
- src/client/src/app/modules/admin/catalog/catalog.module.ts
- src/client/src/app/modules/admin/catalog/components/brand/brand.component.ts
- src/client/src/app/modules/admin/catalog/components/category/category-form/category-form.component.html
- src/client/src/app/modules/admin/catalog/components/category/category-form/category-form.component.ts
- src/client/src/app/modules/admin/catalog/components/category/category.component.html
- src/client/src/app/modules/admin/catalog/components/category/category.component.ts
- src/client/src/app/modules/admin/catalog/models/category.ts
- src/client/src/app/modules/admin/catalog/models/categoryParams.ts
- src/client/src/app/modules/admin/catalog/services/brand.service.ts
- src/client/src/app/modules/admin/catalog/services/category.service.ts
- src/client/src/app/modules/home/welcome/welcome.component.html
- src/client/src/app/modules/home/welcome/welcome.component.ts
Added 
- Category Api Service
- Category Service
- Category Form
- Category  / Category Params models
+ some other minor changes like cleanup & formatting
> Completed Category Component

- src/client/src/app/modules/admin/settings/settings.component.html
- src/client/src/assets/i18n/en.json
- src/client/src/assets/i18n/es.json
- src/client/src/assets/i18n/fr.json
- src/client/src/assets/i18n/ru.json
- src/server/Modules/Identity/Modules.Identity.Core/Helpers/ClaimExtensions.cs
- src/server/Shared/Shared.Core/Constants/Permissions.cs
Also add `group` and `description` for permissions from attributes
> Update: Add ru localization

- src/client/src/app/core/guards/auth.guard.ts
- src/client/src/app/core/interceptors/error.interceptor.ts
- src/client/src/app/core/interceptors/jwt.interceptor.ts
- src/client/src/app/core/services/auth.service.ts
- src/client/src/app/modules/auth/login/login.component.ts
I made some changes to fix the issue #52
> Fixes for bug fluentpos/fluentpos#52

- src/client/src/app/modules/pos/components/customer-selection/customer-selection.component.html
- src/client/src/app/modules/pos/components/customer-selection/customer-selection.component.ts
- src/client/src/app/modules/pos/components/customer-skeleton/customer-skeleton.component.html
- src/client/src/app/modules/pos/components/customer-skeleton/customer-skeleton.component.spec.ts
- src/client/src/app/modules/pos/components/customer-skeleton/customer-skeleton.component.ts
- src/client/src/app/modules/pos/pos.module.ts
- src/client/src/app/modules/pos/services/pos.service.ts
#85 Added Customer Skeleton Loading for POS
> Fluentpos 85

- src/client/src/app/modules/pos/components/cart-skeleton/cart-skeleton.component.html
- src/client/src/app/modules/pos/components/cart-skeleton/cart-skeleton.component.ts
> updates to cart skeleton

- docs/adding-extended-attribute-tutorial.md
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/BaseController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/BrandsController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/CategoriesController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/ExtendedAttributes/BrandExtendedAttributesController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/ExtendedAttributes/CategoryExtendedAttributesController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/ExtendedAttributes/ProductExtendedAttributesController.cs
- src/server/Modules/Catalog/Modules.Catalog.Controllers/Controllers/ProductsController.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Services/IdentityService.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/BaseController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/ExtendedAttributes/RoleExtendedAttributesController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/ExtendedAttributes/UserExtendedAttributesController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/IdentityController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/RolesController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/TokensController.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/UsersController.cs
- src/server/Modules/People/Modules.People/Controllers/BaseController.cs
- src/server/Modules/People/Modules.People/Controllers/CartItemsController.cs
- src/server/Modules/People/Modules.People/Controllers/CartsController.cs
- src/server/Modules/People/Modules.People/Controllers/CustomersController.cs
- src/server/Modules/People/Modules.People/Controllers/ExtendedAttributes/CartExtendedAttributesController.cs
- src/server/Modules/People/Modules.People/Controllers/ExtendedAttributes/CartItemExtendedAttributesController.cs
- src/server/Modules/People/Modules.People/Controllers/ExtendedAttributes/CustomerExtendedAttributesController.cs
- src/server/Shared/Shared.Infrastructure/Controllers/CommonBaseController.cs
- src/server/Shared/Shared.Infrastructure/Extensions/ApplicationBuilderExtensions.cs
- src/server/Shared/Shared.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/server/Shared/Shared.Infrastructure/Shared.Infrastructure.csproj
- src/server/Shared/Shared.Infrastructure/Swagger/Filters/RemoveVersionFromParameterFilter.cs
- src/server/Shared/Shared.Infrastructure/Swagger/Filters/ReplaceVersionWithExactValueInPathFilter.cs
> Feat: Add API versioning

- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/GetAllPagedProductsQuery.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/ProductQueryHandler.cs
- src/server/Shared/Shared.DTOs/Catalogs/Products/PaginatedProductFilter.cs
> Fix: Fix Search Based on Brand and Category

- src/client/src/environments/environment.ts
> change env variable for ng #99

- docs/adding-extended-attribute-tutorial.md
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Brands/Queries/Validators/PaginatedBrandFilterValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Categories/Queries/Validators/PaginatedCategoryFilterValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/ExtendedAttributes/Validators/Brands/PaginatedBrandExtendedAttributeFilterValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/ExtendedAttributes/Validators/Categories/PaginatedCategoryExtendedAttributeFilterValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/ExtendedAttributes/Validators/Products/PaginatedProductExtendedAttributeFilterValidator.cs
- src/server/Modules/Catalog/Modules.Catalog.Core/Features/Products/Queries/Validators/PaginatedProductFilterValidator.cs
- src/server/Modules/Identity/Modules.Identity.Core/Features/ExtendedAttributes/Validators/Roles/PaginatedRoleExtendedAttributeFilterValidator.cs
- src/server/Modules/Identity/Modules.Identity.Core/Features/ExtendedAttributes/Validators/Users/PaginatedUserExtendedAttributeFilterValidator.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/EventLogsController.cs
- src/server/Modules/People/Modules.People.Core/Features/CartItems/Queries/Validators/PaginatedCartItemFilterValidator.cs
- src/server/Modules/People/Modules.People.Core/Features/Carts/Queries/Validators/PaginatedCartFilterValidator.cs
- src/server/Modules/People/Modules.People.Core/Features/Customers/Queries/Validators/PaginatedCustomerFilterValidator.cs
- src/server/Modules/People/Modules.People.Core/Features/ExtendedAttributes/Validators/CartItems/PaginatedCartItemExtendedAttributeFilterValidator.cs
- src/server/Modules/People/Modules.People.Core/Features/ExtendedAttributes/Validators/Carts/PaginatedCartExtendedAttributeFilterValidator.cs
- src/server/Modules/People/Modules.People.Core/Features/ExtendedAttributes/Validators/Customers/PaginatedCustomerExtendedAttributeFilterValidator.cs
- src/server/Shared/Shared.Core/Constants/Permissions.cs
- src/server/Shared/Shared.Core/EventLogging/EventLog.cs
- src/server/Shared/Shared.Core/Extensions/QueryableExtensions.cs
- src/server/Shared/Shared.Core/Interfaces/Services/IEventLogService.cs
- src/server/Shared/Shared.DTOs/Identity/EventLogs/GetEventLogsRequest.cs
- src/server/Shared/Shared.Infrastructure/Extensions/ServiceCollectionExtensions.cs
- src/server/Shared/Shared.Infrastructure/Mappings/EventLogProfile.cs
- src/server/Shared/Shared.Infrastructure/Services/EventLogService.cs
- src/server/Shared/Shared.Infrastructure/Validators/PaginatedEventLogFilterValidator.cs
> Update: Add more properties for EventLog filter

- src/client/src/app/core/shared/components/access-denial/access-denial.component.html
- src/client/src/app/core/shared/components/server-error/server-error.component.html
- src/client/src/app/core/shared/components/server-error/server-error.component.scss
- src/client/src/assets/i18n/en.json
Update Server Error 
Fix Typo Access Denial
> Fluentpos 113

- src/client/src/app/core/api/identity/role-api.service.ts
- src/client/src/app/core/api/identity/user-api.service.ts
- src/client/src/app/core/shared/shared.module.ts
- src/client/src/app/layouts/admin-layout/admin-layout.component.html
- src/client/src/app/modules/admin/identity/components/role/role-form/role-form.component.html
- src/client/src/app/modules/admin/identity/components/role/role-form/role-form.component.ts
- src/client/src/app/modules/admin/identity/components/role/role.component.html
- src/client/src/app/modules/admin/identity/components/role/role.component.ts
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.ts
- src/client/src/app/modules/admin/identity/components/user/user.component.html
- src/client/src/app/modules/admin/identity/components/user/user.component.ts
- src/client/src/app/modules/admin/identity/identity-routing.module.ts
- src/client/src/app/modules/admin/identity/identity.module.ts
- src/client/src/app/modules/admin/identity/models/role.ts
- src/client/src/app/modules/admin/identity/models/roleParams.ts
- src/client/src/app/modules/admin/identity/models/user.ts
- src/client/src/app/modules/admin/identity/models/userParams.ts
- src/client/src/app/modules/admin/identity/services/role.service.ts
- src/client/src/app/modules/admin/identity/services/user.service.ts
> User and Role UI

- src/client/src/app/core/api/identity/identity-api.service.ts
- src/client/src/app/core/shared/shared.module.ts
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.ts
- src/client/src/app/modules/admin/identity/identity.module.ts
- src/client/src/app/modules/admin/identity/models/identityParams.ts
- src/client/src/app/modules/admin/identity/models/resetPassword.ts
- src/client/src/app/modules/admin/identity/models/user.ts
- src/client/src/app/modules/admin/identity/services/identity.service.ts
- src/client/src/app/modules/admin/identity/services/user.service.ts
> Identity Service

- src/client/src/app/core/api/identity/role-api.service.ts
- src/client/src/app/core/shared/components/table/table.component.html
- src/client/src/app/core/shared/components/table/table.component.ts
- src/client/src/app/modules/admin/identity/components/role/permission-form/permission-form.component.html
- src/client/src/app/modules/admin/identity/components/role/permission-form/permission-form.component.ts
- src/client/src/app/modules/admin/identity/components/role/role-form/role-form.component.html
- src/client/src/app/modules/admin/identity/components/role/role-form/role-form.component.ts
- src/client/src/app/modules/admin/identity/components/role/role.component.html
- src/client/src/app/modules/admin/identity/components/role/role.component.ts
- src/client/src/app/modules/admin/identity/identity.module.ts
- src/client/src/app/modules/admin/identity/models/permission.ts
- src/client/src/app/modules/admin/identity/services/role.service.ts
> Role and Permissions

- src/client/src/app/core/shared/components/table/table.component.html
- src/client/src/app/modules/admin/event-logs/event-logs.component.html
- src/client/src/app/modules/admin/event-logs/event-logs.component.ts
> Fluentpos 82

- .github/workflows/sonarqube.yml
#144 
- Create a free account in [SonarQube Cloud](https://sonarcloud.io/)
- Add the private Action Secret Key in [GitHub repository settings](https://github.com/klevisndoka/Evolve/settings/secrets/actions)
ps: One of administrator has to do it, I do not have access.
> Added SonarQube Action

- src/client/src/app/core/api/identity/user-api.service.ts
- src/client/src/app/core/shared/components/table/table.component.html
- src/client/src/app/core/shared/components/table/table.component.ts
- src/client/src/app/modules/admin/identity/components/role/permission-form/permission-form.component.ts
- src/client/src/app/modules/admin/identity/components/user/user-role-form/user-role-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-role-form/user-role-form.component.ts
- src/client/src/app/modules/admin/identity/components/user/user.component.html
- src/client/src/app/modules/admin/identity/components/user/user.component.ts
- src/client/src/app/modules/admin/identity/identity.module.ts
- src/client/src/app/modules/admin/identity/models/userRole.ts
- src/client/src/app/modules/admin/identity/services/user.service.ts
> User Roles and Custom Table

- src/client/src/app/core/api/identity/user-api.service.ts
- src/client/src/app/modules/admin/identity/components/user/user-role-form/user-role-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-role-form/user-role-form.component.ts
- src/client/src/app/modules/admin/identity/models/userRole.ts
- src/client/src/app/modules/admin/identity/services/user.service.ts
- src/server/Modules/Identity/Modules.Identity.Core/Abstractions/IUserService.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Services/UserService.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/UsersController.cs
- src/server/Shared/Shared.DTOs/Identity/Users/UserRolesRequest.cs
- src/server/Shared/Shared.DTOs/Identity/Users/UserRolesResponse.cs
> API & NG: Update Roles to User

- src/client/src/app/layouts/admin-layout/admin-layout.component.ts
> NG: Fixed ChangeDetectionStrategy

- src/client/src/app/modules/admin/identity/components/role/role-permission-form/role-permission-form.component.html
- src/client/src/app/modules/admin/identity/components/role/role.component.ts
- src/client/src/app/modules/admin/identity/components/user/user-role-form/user-role-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user.component.ts
- src/client/src/styles.scss
> Dialog panel ui fixes

- src/server/Modules/Inventory/Modules.Inventory.Core/Extensions/ServiceCollectionExtensions.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Commands/ExtendedAttributeCommandHandler.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Events/ExtendedAttributeAddedEvent.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Events/ExtendedAttributeEventHandler.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Events/ExtendedAttributeRemovedEvent.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Events/ExtendedAttributeUpdatedEvent.cs
- src/server/Shared/Shared.Core/Features/ExtendedAttributes/Queries/ExtendedAttributeQueryHandler.cs
- src/server/Shared/Shared.Core/Utilities/TypeUtilities.cs
- src/server/Shared/Shared.Infrastructure/EventLogging/EventLogger.cs
- src/server/Shared/Shared.Infrastructure/Extensions/ModuleDbContextExtensions.cs
Example:
instead of `ExtendedAttributeAddedEvent'2`
> Fix: Fix getting generic type name

- src/client/src/app/core/shared/components/table/table.component.html
- src/client/src/app/modules/admin/identity/components/role/role-permission-form/role-permission-form.component.html
- src/client/src/app/modules/admin/identity/components/role/role-permission-form/role-permission-form.component.ts
> Role Permission Form Update

- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.scss
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.ts
- src/client/src/app/modules/admin/identity/models/user.ts
- src/server/Modules/Identity/Modules.Identity.Core/Abstractions/IUserService.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Mappings/UserProfile.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Services/IdentityService.cs
- src/server/Modules/Identity/Modules.Identity.Infrastructure/Services/UserService.cs
- src/server/Modules/Identity/Modules.Identity/Controllers/UsersController.cs
- src/server/Shared/Shared.DTOs/Identity/RegisterRequest.cs
- src/server/Shared/Shared.DTOs/Identity/Users/UpdateUserRequest.cs
- src/server/Shared/Shared.DTOs/Identity/Users/UserResponse.cs
> Fix Create and Update User

- src/client/src/app/modules/admin/catalog/components/brand/brand-form/brand-form.component.html
- src/client/src/app/modules/admin/catalog/components/category/category-form/category-form.component.html
- src/client/src/app/modules/admin/catalog/components/product/product-form/product-form.component.html
- src/client/src/app/modules/admin/identity/components/role/role-form/role-form.component.html
- src/client/src/app/modules/admin/identity/components/user/user-form/user-form.component.html
- src/client/src/app/modules/admin/people/components/customer/customer-form/customer-form.component.html
> Small UI Changes

- src/client/src/app/modules/admin/catalog/components/category/category.component.ts
Corrected minor typo in code.
Issue [#203](https://github.com/fluentpos/fluentpos/issues/203)
> fix(category): minor typo in code
